# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nats < Formula
  desc "NATS utility"
  homepage "https://github.com/nats-io/nats"
  version "0.0.27"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/nats-io/natscli/releases/download/v0.0.27/nats-0.0.27-darwin-arm64.zip"
      sha256 "4cfc7ced4d0c1000c11d2f7e9842130e4537ec77893043c89b98386101137865"

      def install
        bin.install "nats"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/nats-io/natscli/releases/download/v0.0.27/nats-0.0.27-darwin-amd64.zip"
      sha256 "3e4f9743b93c7861990124dd214c8711dec1c323022e24a863e32e393c00bfd0"

      def install
        bin.install "nats"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/nats-io/natscli/releases/download/v0.0.27/nats-0.0.27-linux-arm6.zip"
      sha256 "6e700e63e49d7fc5769b9837780eaa1bd129e2c92d4ea461071ff2b62436a2ac"

      def install
        bin.install "nats"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nats-io/natscli/releases/download/v0.0.27/nats-0.0.27-linux-arm64.zip"
      sha256 "4138f6347cad4fe564eeb4413ac68b14e5997ce28245bffa5e70d3af1315c71b"

      def install
        bin.install "nats"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/nats-io/natscli/releases/download/v0.0.27/nats-0.0.27-linux-amd64.zip"
      sha256 "0b4b461dda00af3bfdcb7d1cca890377e3737522c9f01df50218cd7f9c8e80a5"

      def install
        bin.install "nats"
      end
    end
  end

  test do
    system "#{bin}/nats --version"
  end
end
