# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nsc < Formula
  desc "A tool for creating NATS account and user access configurations"
  homepage "https://github.com/nats-io/nsc"
  version "2.2.0"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/nats-io/nsc/releases/download/2.2.0/nsc-darwin-amd64.zip"
    sha256 "52cd87d2b8221c24036e32c430a01578720033d5689e38e70e8e804d5812ee6d"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/nats-io/nsc/releases/download/2.2.0/nsc-linux-amd64.zip"
    sha256 "13890af56e0342e2b890f4a2672d34f0c86e73c8d58d914df5dcf7f62e0ce6a2"
  end

  def install
    bin.install "nsc"
  end

  test do
    system "#{bin}/nsc --version"
  end
end
