# This file was generated by GoReleaser. DO NOT EDIT.
class Nsc < Formula
  desc "A tool for creating NATS account and user access configurations"
  homepage "https://github.com/nats-io/nsc"
  version "0.4.2"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/nats-io/nsc/releases/download/0.4.2/nsc-darwin-amd64.zip"
    sha256 "8326838182b98640a43d34d4bd7ea900823bc16352d86af7d6150076211e96cc"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/nats-io/nsc/releases/download/0.4.2/nsc-linux-amd64.zip"
      sha256 "fbf77a29c7db030ba75436c701dadc4f2e2a77e3ba0bfa8eb6cae889849b1ab2"
    end
  end

  def install
    bin.install "nsc"
  end

  test do
    system "#{bin}/nsc --version"
  end
end
